alias gs='git status'
alias push='git push'
alias pushf='git push --force'
alias pull='git pull'
alias pullf='git pull --force'
alias gc='git commit'
alias gri='git rebase -i'
alias ga='git add .'
alias rc='nano ~/.zshrc'
alias gch='git checkout'
alias gcln='git clone'
alias grro='git remote rename origin'
alias gra='git remote add'
alias grau='git remote add upstream'
alias kconfig='~/Public/k8s_swap.sh'
alias ..="cd .."
alias venv="python3 -m venv venv"
alias activate="source venv/bin/activate"
alias arbol="git log --all --graph --decorate --oneline"
alias pip3="python3 -m pip"
alias SH="nano ~/.zshrc"
alias RS="exec $SHELL"
export keylol=""
eval "$(starship init zsh)"
